---
# yamllint disable rule:line-length
lookup_options:
  jenkinsx::casc:
    merge:
      strategy: deep
      merge_hash_arrays: false
      sort_merged_arrays: false
jenkinsx::casc:
  credentials:
    system:
      domainCredentials:
        - credentials:
            - string:
                id: slack-default-channel
                scope: GLOBAL
                description: Default slack channel
                secret: dmj-jhoblitt-larry
            - string:
                id: slack-channel-prefix
                scope: GLOBAL
                description: Prefix for generated slack channels
                secret: dmjjl
